version: '3'
services:
  superset:
    image: apache-superset
    env_file:
      - /superset.env
    ports:
      - "8088:8088"
    volumes:
      - ./superset-data:/app/superset_home
    networks:
      - hadoop-network
networks:
  hadoop-network:
    external:
      name: attijari_project_db